# 1. Numpy and Linear Algebra (선형대수)

- 수치 data 를 다루는데 효율적이고 높은 성능 제공

- 각종 수학적 함수 제공

- Python scientific library 들이 Numpy 기반으로 구축

### ndarray

- n-dimensional array (다차원 배열 객체) 로 구성 

In [1]:
import sys
import numpy as np

In [3]:
# 벡터
x = np.array([1,2,3])

print("x = ", x)

x =  [1 2 3]


In [5]:
# matrix
y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print("array dimension {}".format(y.shape))

array dimension (3, 3)


In [7]:
x = np.array([[[1, 2], 
               [3, 2]], 
              [[1, 7], 
               [5, 4]]])

x.shape

(2, 2, 2)

### 전치행렬 (Transposed Matrix)

In [8]:
# matrix transpose
A = np.arange(9).reshape((3,3))
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
np.transpose(A)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])